-- ==========================================
-- 1. Информация о пользователях
-- ==========================================
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(256) NOT NULL,
    name  VARCHAR(250)  NOT NULL
);

-- ==========================================
-- 2. Информация категориях
-- ==========================================
CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) UNIQUE NOT NULL
);

-- ==========================================
-- 3. Информация о событиях
-- ==========================================
-- Содержит следующие поля:
-- id события
-- title - заголовок события
-- annotation - краткое описание события
-- confirmedRequests - количество одобренных запросов на участие в событии
-- id категории
-- id пользователя, который опубликовал событие
-- description - полное описание
-- date - дата события
-- createdOn - дата создания события
-- publishedOn - дата публикации события
-- lat и lon - долгота и ширина места проведения события
-- paid - нужно ли оплачивать участие
-- participantLimit - максимальное количество участников
-- requestModeration - модерация заявок
-- state("PENDING", "PUBLISHED","CANCELED")
-- views - количество посмотревшихся события
-- ==========================================
CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120)  NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    confirmed_requests BIGINT,
    category_id        BIGINT        NOT NULL,
    user_id            BIGINT        NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    date               TIMESTAMP WITHOUT TIME ZONE,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    lat                FLOAT         NOT NULL,
    lon                FLOAT         NOT NULL,
    paid               BOOLEAN       NOT NULL,
    participant_limit  INT           NOT NULL,
    request_moderation BOOLEAN       NOT NULL,
    state              VARCHAR(30)   NOT NULL,
    views              BIGINT,
    FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ==========================================
-- 4. Запросы пользователей на участие в событиях
-- ==========================================
-- Содержит следующие поля:
-- id заявки
-- event_id - id события
-- user_id - id пользователя, который отправил заявку
-- created - дата и время отправки заявки
-- status("PENDING", "PUBLISHED","CANCELED")
-- ==========================================
CREATE TABLE IF NOT EXISTS requests
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT      NOT NULL,
    user_id  BIGINT      NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE,
    state    VARCHAR(30) NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);